#!/usr/bin/env php

<?php

// 1. Створити базовий шлях
use Web\Framework\Console\Kernel;

define('BASE_PATH', dirname(__FILE__));
// 2. Добавить автозагрузчик
require_once BASE_PATH . '/vendor/autoload.php';
// 3. Добавить контейнер
$container = require BASE_PATH . '/config/services.php';
// 4. Отримати Kernel консолі з контейнера
$kernel = $container->get(Kernel::class);
// 5. Визвати метод handel в Kernel, вернути код статуса консольного додатку
$status = $kernel->handle();
// 6. Вийти з отриматим кодом статуса
exit($status);